name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Replace API key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Replacing API_KEY in script.js"
          sed -i 's/YOUR_API_KEY/'"$API_KEY"'/g' script.js

      - name: Deploy to server
        run: |
          echo "Deploying with API_KEY"

          # 假設你要使用scp將文件複製到遠程服務器
          scp -r . user@server:/path/to/deploy

          # 或者使用rsync同步文件
          rsync -avz . user@server:/path/to/deploy
